services:
  postgres:
    image: postgres:18
    container_name: estoque-hospital-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: estoque_hospital
      POSTGRES_USER: estoque_app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql

    ports:
      - "5433:5432"

volumes:
  postgres_data: