spring.datasource.url=${HOMOLOG_DB_URL}
spring.datasource.username=${HOMOLOG_DB_USERNAME}
spring.datasource.password=${HOMOLOG_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true